config:
  target: "http://localhost:3000"
  phases:
    - duration: 30
      arrivalRate: 10
      name: Warm up
    - duration: 60
      arrivalRate: 10
      rampTo: 100
      name: Ramp up load
    - duration: 60
      arrivalRate: 100
      rampTo: 1000
      name: Ramp up load

scenarios:
  - name: "Get all products"
    flow:
      - get:
          url: "/products"